### PR TITLE
Blink PR1 w/build fix

### PR DESCRIPTION
**Pull request by dwillmer**

### CODE REVIEW

**Comment by jasongrout** [comment]
@dwillmer, we shouldn't be committing node_modules or lib/.  Those should be added at the build/packaging step.

**Comment by dwillmer** [comment]
node_modules isn't present, but lib is required temporarily, or at least that's the way we're building with the other repos.

both are in the gitignore though.

**Comment by jasongrout** [comment]
this commit adds the node_modules: https://github.com/dwillmer/jupyter-js-terminal/commit/9ac362c3b4d2da5b3eb2ecba145b926ae92dcd27

**Comment by dwillmer** [comment]
...and the ones after deletes them.

**Comment by jasongrout** [comment]
ah.  Can you rebase to squash those two commits so they don't appear in the history?

**Comment by jasongrout** [comment]
no need to bloat the repo size.

**Comment by dwillmer** [comment]
Done

**Comment by blink1073** [comment]
@jasongrout, any objection to merge and iterate?

**Comment by jasongrout** [comment]
Thanks.  Yes, let's iterate from here.

**Pull request merged**
